### ISSUE TITLE
Example not working - and fix

### ISSUE THREAD

**Issue by somebee** [jonbjornn/imba-rails-test#1]
Hi there. The cause of the stuttering is actually the lack of css. As you can see [here](https://github.com/jonbjornn/imba-rails-test/blob/master/javascripts/dynamic.imba#L19-L21), the onmousemove of the example is defined on the sample tag. Since it has no styles, it is as small as the relatively positioned inner content. So whenever the mouse moves outside the headlines etc - x and y positions are never updated.

If you add the following css, it should work without problems.

```css
html,body,._sample {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
}
.circle { position: absolute; }
```
The example should work. Why the line $$(body).append seems to throw an error still beats me, I'm looking into it.
